# Don't forget to run
#
#     pkg> dev ..
#
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MyCopierTemplate = "c32aea7f-d2ea-5f36-99f4-d48efa7ecb06"

[compat]
Documenter = "1"
